### PR TITLE
Update to Grunt 0.4 & Fix Missing Partials Issue

### PR DESCRIPTION
**Pull request by ericclemmons**
Refs #58, #59, #45, and perhaps #60!

Since Grunt 0.4 is coming soon, this project is using that for future integration with [Grunttacular](https://npmjs.org/package/gruntacular) and Yeoman-derived grunt plugins.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@kwhitley This PR is a pretty large cleanup.  I was going to see how I like `Gruntfile.coffee` as the final commit, but otherwise, this de-couples several `watch` tasks, namespaces views (so we can have easier cross-module partial usage), and some other small fixes.

**Comment by kwhitley** [comment]
looking it over...

**Comment by facultymatt** [comment]
@ericclemmons I tried a fresh install using the new master branch with the above merges and I'm running into serious issues:

**Coffee script needs compiling, not a big issue deal but not mentioned in documentation... making it harder to get started.**

**Error running grunt server**
Even after compiling and changing gruntfile.js to grunt.js, running `grunt server` fails, with the following errors:

```
$ grunt server 
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.
```

Using force fails too. 

Any thoughts? Were you guys able to run these changes successfully?

**Comment by ericclemmons** [comment]
It's just `grunt` now, so the `server` task that grunt comes with can be left alone.  I need to update the docs.

Also, `grunt 0.4` should be automatically compiling `Gruntfile.coffee`.  Is that not the case for you?  (I assume the `npm install` went fine)

**Comment by facultymatt** [comment]
Ok, thanks @ericclemmons, this is helpful. A few observations
- Gruntfile.coffee is NOT auto compiling. I need to compile it and remane it to grunt.js (are you using coffeesript automatic compile? ie: `coffee --watch --compile Gruntfile.coffee` - this will autocompile but its a bit clunky, as it requires the user to start it in a separate terminal window)
- After above step, running `grunt` works as planned. 
- Does this mean there is no more `grunt build` needed? I thought that `build` had different settings than `server`, such as smushit, etc. How is this handled now? 
- Grunt defaults to port 35729 for LiveReload... which doesn't work. Can you manually set this to in the gruntfile? 
- the procfile: npm start fails... moving the scripts `web: ./node_modules/.bin/grunt build && node src/server/server` into the profile works! 

This being said, seems the following issues need to be addressed:
[ ] move `web: ./node_modules/.bin/grunt build && node src/server/server` to procfile and remove from package.json
[ ] Setup gruntfile.coffee to auto compile (or provide a precompiled version for users)
[ ] Adjust documentation as needed for gruntfile compile and `grunt server` vs. `grunt` vs. `gruntfile`
[ ] Adjust gruntfile default livereload port in gruntfile.coffee

ps. npm install did indeed go fine!

**Comment by facultymatt** [comment]
@ericclemmons was just playing around with Grunt and noticed something odd... It doesn't appear to matter what is in grunt.js, only that this file exists, when running `grunt` command - ie: running grunt auto-compiles the `Gruntfile.coffee` file as you stated. But, it seems that having a blank file named grunt.js is necessary for this to happen. 

To test this 
- I deleted all code from grunt.js and then ran `grunt` successfully.
- I changed the default port to 4000 in Gruntfile.coffee, but not in grunt.js, then ran `grunt` and the server started on port 4000
- I deleted the file grunt.js and ran `grunt` and it failed, saying the file grunt.js was not found. 

Hope this is helpful!

**Pull request merged**
