### PR TITLE
[WIP] Starter App Cleanup

### PR DESCRIPTION
**Pull request by kwhitley**
Refs #35 
## TODO
- [x] Convert home to show server/client installed modules
- [x] Configure and test regarde targets (I don't believe the root folder path watch target works)
- [x] Remove any extra tasks
- [x] Fix angular templates error in dev mode

### CODE REVIEW

**Comment by kwhitley** [comment]
Still a [WIP]... have to run out for a bit but can continue tonight.

**Comment by ericclemmons** [comment]
I was going to keep working on it for you, just wanted to catch up to where you were!

**Comment by kwhitley** [comment]
Cool! You'll make faster progress anyway :) see todos for issues I know of so far...

**Comment by ericclemmons** [comment]
Fixed several issues that we've been having for a while (see commits).

Not sure what the problem is with angular templates in dev mode.  It would always 404 since the file doesn't exist.  Unless I approved the following PR to automatically add it to the concat task:

> https://github.com/ericclemmons/grunt-angular-templates/pull/17

**Comment by ericclemmons** [comment]
Oh yea, here's how it looks right now:

> Genesis Skeleton

**Comment by kwhitley** [comment]
Hell yes!  Looks beautiful! :+1:

**Comment by ericclemmons** [comment]
Holy crap, there **will** be a demo tomorrow!!

**Comment by kwhitley** [comment]
```
$ grunt server
Running "clean:dist" (clean) task

Running "jshint:files" (jshint) task
>> 9 files lint free.

Running "karma:unit" (karma) task
INFO [karma]: Karma server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: Cannot start PhantomJS
    execvp(): No such file or directory

INFO [launcher]: Trying to start PhantomJS again.
ERROR [launcher]: Cannot start PhantomJS
    execvp(): No such file or directory

INFO [launcher]: Trying to start PhantomJS again.
ERROR [launcher]: Cannot start PhantomJS
    execvp(): No such file or directory

Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by kwhitley** [comment]
If this will run by default, may want to include a `brew install phantomjs` line to the `README.md`.

**Comment by ericclemmons** [comment]
I'd be interested in running this purely through jasmine, and letting the user choose to use phantomjs vs chrome vs ie.

Maybe there's a grunt-jasmine we should be running through karma, or separately?  

## 

Eric Clemmons
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ericclemmons** [comment]
Ok, I think I'm done.  I'm **really** proud of the work we did on this, and I think it's an **awesome** starter kit that solves sooooo many problems.

I'm eager to update Genesis Skeleton's webpage to match.  Plus, I think I should kill the yeoman installer, too.  We're not doing Yeoman.

**Pull request merged**
